--Need foreign key restraints in the DB
--In order to build a database using this file do .read relativepath/schema.sql
PRAGMA foreign_keys = ON;

CREATE TABLE PERSON(SSN INT PRIMARY KEY NOT NULL,PNAME TEXT NOT NULL,AGE INT,DOB TEXT, EMAIL TEXT);

CREATE TABLE DEBT(ID INT PRIMARY KEY NOT NULL,ACCT INT NOT NULL,DOLLAS INT NOT NULL,SSN INT NOT NULL,
FOREIGN KEY(SSN) REFERENCES PERSON(SSN));

CREATE TABLE PAYMENT(ID INT PRIMARY KEY NOT NULL,DATE TEXT,DOLLAS INT NOT NULL,ACCT INT NOT NULL,
SSN INT NOT NULL,FOREIGN KEY(SSN) REFERENCES PERSON(SSN));

CREATE TABLE CREDIT(ID INT PRIMARY KEY NOT NULL,DATE TEXT NOT NULL,SCORE INT NOT NULL,SSN INT NOT NULL,
FOREIGN KEY(SSN) REFERENCES PERSON(SSN));